export const SOCKET_EVENTS = {
  // User Events
  CONNECTION: "connection",
  USER_ONLINE: "USER_ONLINE",
  USER_OFFLINE: "USER_OFFLINE",

  // Project  Events
  JOIN_PROJECT: "JOIN_PROJECT",
  SEND_MESSAGE: "SEND_MESSAGE",
  TEAM_MESSAGE: "TEAM_MESSAGE",
  TEAM_MESSAGE_DELETED: "TEAM_MESSAGE_DELETED",
  TEAM_MESSAGE_EDITED: "TEAM_MESSAGE_EDITED",

  PROJECT_MESSAGE: "PROJECT_MESSAGE",
  TEST_MESSAGE: "TEST_MESSAGE",

  //Task Events
  TASK_UNASSIGNED: "TASK_UNASSIGNED",
  TASK_ASSIGNED: "TASK_ASSIGNED",
  TASK_UPDATED: "TASK_UPDATED",

  // Notification Events
  TEAM_MESSAGE_NOTIFICATION: "TEAM_MESSAGE_NOTIFICATION",
  
  UPDATE_NOTIFICATION_COUNT: "UPDATE_NOTIFICATION_COUNT",
  NOTIFICATION_COUNT: "NOTIFICATION_COUNT",
} as const;

export type SocketEvent = (typeof SOCKET_EVENTS)[keyof typeof SOCKET_EVENTS];
